PRICES = 'prices'
IATA_CODE = 'iataCode'
LOWEST_PRICE = 'lowestPrice'
CITY = 'city'
ID = 'id'

DAYS_TO_SEARCH = 3

FLIGHT_SEARCH_URL = "https://test.api.amadeus.com/v2"
FLIGHT_SEARCH_TOKEN_ENDPOINT = "https://test.api.amadeus.com/v1/security/oauth2/token"

SHEETY_API_URL = "SHEETY_API_URL"
AMADEUS_API_KEY = "AMADEUS_API_KEY"
AMADEUS_SECRET = "AMADEUS_SECRET"
TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN"
TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID"
TWILIO_VIRTUAL_NUMBER = "TWILIO_VIRTUAL_NUMBER"
